<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>eShop.IntegrationEventLogEF</RootNamespace>
    <IsPublishable>false</IsPublishable>
     <!-- Semantic Versioning #todo might not be necessary if containerImageTags is used  -->
    <Version>1.0.0</Version>
    <!-- Container Configuration -->
    <ContainerRepository>saadisfy/eShop/integration-event-log-ef</ContainerRepository>
    <ContainerImageTag>1.0.0</ContainerImageTag>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventBus\EventBus.csproj" />
  </ItemGroup>

</Project>