apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
  - name: tcp
    port: {{ .Values.redis.service.port }}
    targetPort: tcp
    protocol: TCP
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
