apiVersion: v2
name: eshop-microservice-base
version: 0.1.0
description: A base Helm chart template for eShop microservices deployment
type: application
appVersion: "1.0.0"
keywords:
  - eshop
  - microservices
  - dotnet
  - ssl
  - cert-manager
maintainers:
  - name: Saad Masood
    email: saad.masood@student.kit.edu 