apiVersion: v2
name: webapp
version: 0.1.0
description: eShop Web Application using basechart dependency
type: application
appVersion: "1.0.0"
dependencies:
  - name: basechart
    version: "1.0.1"
    repository: "oci://ghcr.io/saadisfy"
    alias: base