{{- /* Generate Redis connection string secret */ -}}
{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.eshop.sharedServices.redis.secretRefName }} # is set globally
type: Opaque
data:
  ConnectionStrings__redis: {{ printf "%s-%s:%d,password=%s" .Release.Name .Values.global.eshop.sharedServices.redis.serviceName (.Values.global.eshop.sharedServices.redis.port| int) .Values.global.eshop.sharedServices.redis.auth.password | b64enc | quote }}
{{- end }}

{{- /* Generate RabbitMQ connection string secret */ -}}
{{- if .Values.rabbitmq.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.eshop.sharedServices.rabbitmq.secretRefName }} # is set globally
type: Opaque
data:
  ConnectionStrings__eventbus: {{ printf "amqp://%s:%s@%s-%s:%d" .Values.global.eshop.sharedServices.rabbitmq.auth.username .Values.global.eshop.sharedServices.rabbitmq.auth.password .Release.Name .Values.global.eshop.sharedServices.rabbitmq.serviceName (.Values.global.eshop.sharedServices.rabbitmq.port| int) | b64enc | quote }}
{{- end }}

