<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableConfigurationBindingGenerator>true</EnableConfigurationBindingGenerator>
    <PublishAot Condition="'$(EnableAotPublishing)' == 'true'">true</PublishAot>
     <!-- Semantic Versioning #todo might not be necessary if containerImageTags is used  -->
    <Version>1.0.0</Version>
    <!-- Container Configuration -->
    <ContainerRepository>saadisfy/eShop/order-processor</ContainerRepository>
    <ContainerImageTag>1.0.0</ContainerImageTag>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
  </ItemGroup>
</Project>
