apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  POSTGRES_HOST_AUTH_METHOD: {{ .Values.postgresql.auth.hostAuthMethod | quote }}
  POSTGRES_INITDB_ARGS: {{ .Values.postgresql.auth.initdbArgs | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.postgresql.monitoring.otelEndpoint | quote }}
  OTEL_SERVICE_NAME: "postgres"
