apiVersion: v1
kind: Service
metadata:
  name: {{ include "eshop-microservice.fullname" . }}
  labels:
    {{- include "eshop-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "eshop-microservice.targetPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "eshop-microservice.selectorLabels" . | nindent 4 }} 