apiVersion: v2
name: payment-processor
version: 0.1.0
description: eShop Payment Processor microservice using basechart dependency
type: application
appVersion: "1.0.0"
dependencies:
  - name: basechart
    version: "1.0.1"
    repository: "oci://ghcr.io/saadisfy"
    alias: base