<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
     <!-- Semantic Versioning #todo might not be necessary if containerImageTags is used  --> 
    <Version>1.0.0</Version>
    <!-- Container Configuration -->
    <ContainerRepository>saadisfy/eShop/payment-processor</ContainerRepository>
    <ContainerImageTag>1.0.0</ContainerImageTag>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\eShop.ServiceDefaults\eShop.ServiceDefaults.csproj" />
    <ProjectReference Include="..\EventBusRabbitMQ\EventBusRabbitMQ.csproj" />
  </ItemGroup>

</Project>
