{{- /* Generate PostgreSQL connection string secret */ -}}
{{- $globalPostgresql := .Values.global.eshop.sharedServices.postgresql | default dict -}}
{{- $localPostgresql := .Values.sharedServices.postgresql | default dict -}}
{{- $finalPostgresql := deepCopy $globalPostgresql | mergeOverwrite $localPostgresql -}}

{{- if and $finalPostgresql.enabled $finalPostgresql.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $finalPostgresql.secretRefName }}
type: Opaque
data:
  ConnectionStrings__{{ $finalPostgresql.auth.database }}: {{ printf "Host=%s;Port=%d;Database=%s;Username=%s;Password=%s" (include "application.postgresqlServiceName" .) ($finalPostgresql.port | int) $finalPostgresql.auth.database $finalPostgresql.auth.username $finalPostgresql.auth.password | b64enc | quote }}
{{- end }}